### ISSUE TITLE
Migrate to broccoli-plugin for base class

### ISSUE THREAD

**Issue by theroncross** [rwjblue/broccoli-file-remover#9]
I'm getting the following on my builds:
```
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: Remover
```
which seems to be popping up from the (deprecated) `broccoli-writer` dependency. https://github.com/broccolijs/broccoli-writer/blob/master/index.js

I'm happy to work on an update, but would require some guidance. As a starting point, how do we feel about the approach in [broccoli-rm](https://github.com/liftM/broccoli-rm/blob/master/index.coffee)?

**Comment by rwjblue** [comment]
In general I think it would be better to refactor to using `broccoli-funnel` with an `exclude` instead. We could change the internals to do just that if we think that this package adds some value over `new Funnel(someDir, { exclude: [....] })` but I'm not super sure that it does...

**Comment by rwjblue** [comment]
@turbo87 - Thoughts here? I think you recently mentioned this to me as well...

**Comment by Turbo87** [comment]
yeah, replacing with funnel seems to be the best way forward. I did something like that in https://github.com/sir-dunxalot/ember-cli-concat/pull/39.

steps that need to be taken:

- [x] deprecate this package
- [x] write a small migration section into the README
